# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SerialComm.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(577, 439)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.comboBox_portas = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_portas.sizePolicy().hasHeightForWidth())
        self.comboBox_portas.setSizePolicy(sizePolicy)
        self.comboBox_portas.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBox_portas.setObjectName("comboBox_portas")
        self.gridLayout_7.addWidget(self.comboBox_portas, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_7.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboBox_bauds = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_bauds.setObjectName("comboBox_bauds")
        self.comboBox_bauds.addItem("")
        self.comboBox_bauds.addItem("")
        self.gridLayout_7.addWidget(self.comboBox_bauds, 1, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox, 0, QtCore.Qt.AlignLeft)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.btn_conectar = QtWidgets.QPushButton(Form)
        self.btn_conectar.setMaximumSize(QtCore.QSize(90, 27))
        self.btn_conectar.setObjectName("btn_conectar")
        self.gridLayout_13.addWidget(self.btn_conectar, 0, 1, 1, 1)
        self.btn_desconectar = QtWidgets.QPushButton(Form)
        self.btn_desconectar.setMaximumSize(QtCore.QSize(90, 27))
        self.btn_desconectar.setObjectName("btn_desconectar")
        self.gridLayout_13.addWidget(self.btn_desconectar, 1, 1, 1, 1)
        self.btn_atualizar = QtWidgets.QPushButton(Form)
        self.btn_atualizar.setMaximumSize(QtCore.QSize(50, 27))
        self.btn_atualizar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imagens/icons8-atualizações-disponíveis-40.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_atualizar.setIcon(icon)
        self.btn_atualizar.setObjectName("btn_atualizar")
        self.gridLayout_13.addWidget(self.btn_atualizar, 1, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_13)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.comandoLabel = QtWidgets.QLabel(Form)
        self.comandoLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.comandoLabel.setObjectName("comandoLabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.comandoLabel)
        self.comandoLineEdit = QtWidgets.QLineEdit(Form)
        self.comandoLineEdit.setObjectName("comandoLineEdit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comandoLineEdit)
        self.verticalLayout.addLayout(self.formLayout_3)
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 555, 250))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.text_log = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents_2)
        self.text_log.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.text_log.setObjectName("text_log")
        self.verticalLayout_3.addWidget(self.text_log)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.scrollArea)
        self.btn_sair = QtWidgets.QPushButton(Form)
        self.btn_sair.setMaximumSize(QtCore.QSize(70, 16777215))
        self.btn_sair.setObjectName("btn_sair")
        self.verticalLayout.addWidget(self.btn_sair, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        self.btn_sair.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "SerialComm @dfso"))
        self.groupBox.setTitle(_translate("Form", "Conexão"))
        self.label.setText(_translate("Form", "Porta"))
        self.label_2.setText(_translate("Form", "Baud Rate"))
        self.comboBox_bauds.setItemText(0, _translate("Form", "9600"))
        self.comboBox_bauds.setItemText(1, _translate("Form", "115200"))
        self.btn_conectar.setText(_translate("Form", "Conectar"))
        self.btn_desconectar.setText(_translate("Form", "Desconectar"))
        self.btn_atualizar.setToolTip(_translate("Form", "Atualizar lista de portas"))
        self.comandoLabel.setText(_translate("Form", "Comando"))
        self.btn_sair.setText(_translate("Form", "&Sair"))

