#############################################################################
# Generated by PAGE version 4.13
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


#############################################################################
## vTcl Code to Load User Images see vTcl:save2 in file.tcl

catch {package require Img}

foreach img {

        {{[file join / home dfso devel python TK serial_comm imgs icons8-atualizações-disponíveis-40.png]} {user image} user {}}

            } {
# from vTcl:image:dump_create_image_footer
    eval set _file [lindex $img 0]
    vTcl:image:create_new_image\
        $_file [lindex $img 1] [lindex $img 2] [lindex $img 3]
}

if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top37
    }
    namespace eval ::widgets::$base {
        set dflt,origin 1
        set runvisible 1
    }
    set site_3_0 $base.lab39
    set site_3_0 $base.lab45
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x450
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 1
    wm maxsize $top 600 450
    wm minsize $top 600 450
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "SerialComm @dfso"
    vTcl:DefineAlias "$top" "janela" vTcl:Toplevel:WidgetProc "" 1
    labelframe $top.lab39 \
        -foreground black -text Conexão -background {#d9d9d9} -height 95 \
        -highlightcolor black -width 330 
    vTcl:DefineAlias "$top.lab39" "Labelframe1" vTcl:WidgetProc "janela" 1
    set site_3_0 $top.lab39
    label $site_3_0.lab40 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Porta 
    vTcl:DefineAlias "$site_3_0.lab40" "Label1" vTcl:WidgetProc "janela" 1
    ttk::combobox $site_3_0.tCo41 \
        -textvariable combobox -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo41" "combobox_portas" vTcl:WidgetProc "janela" 1
    ttk::combobox $site_3_0.tCo43 \
        -textvariable combobox -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo43" "combobox_bauds" vTcl:WidgetProc "janela" 1
    label $site_3_0.lab41 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Baud Rate} 
    vTcl:DefineAlias "$site_3_0.lab41" "Label2" vTcl:WidgetProc "janela" 1
    place $site_3_0.lab40 \
        -in $site_3_0 -x 10 -y 20 -anchor nw -bordermode ignore 
    place $site_3_0.tCo41 \
        -in $site_3_0 -x 140 -y 20 -anchor nw -bordermode ignore 
    place $site_3_0.tCo43 \
        -in $site_3_0 -x 140 -y 50 -anchor nw -bordermode ignore 
    place $site_3_0.lab41 \
        -in $site_3_0 -x 10 -y 50 -anchor nw -bordermode ignore 
    labelframe $top.lab45 \
        -foreground black -text Ações -background {#d9d9d9} -height 95 \
        -highlightcolor black -width 240 
    vTcl:DefineAlias "$top.lab45" "Labelframe2" vTcl:WidgetProc "janela" 1
    set site_3_0 $top.lab45
    button $site_3_0.but47 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Desconectar 
    vTcl:DefineAlias "$site_3_0.but47" "btn_desconectar" vTcl:WidgetProc "janela" 1
    button $site_3_0.but48 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -image [vTcl:image:get_image [file join / home dfso devel python TK serial_comm imgs icons8-atualizações-disponíveis-40.png]] 
    vTcl:DefineAlias "$site_3_0.but48" "btn_atualizar" vTcl:WidgetProc "janela" 1
    button $site_3_0.but49 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Conectar 
    vTcl:DefineAlias "$site_3_0.but49" "btn_conectar" vTcl:WidgetProc "janela" 1
    place $site_3_0.but47 \
        -in $site_3_0 -x 10 -y 50 -anchor nw -bordermode ignore 
    place $site_3_0.but48 \
        -in $site_3_0 -x 120 -y 20 -width 104 -relwidth 0 -height 54 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but49 \
        -in $site_3_0 -x 10 -y 20 -width 100 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    text $top.tex39 \
        -background white -font TkTextFont -foreground black -height 292 \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -undo 1 \
        -width 576 -wrap word 
    .top37.tex39 configure -font TkTextFont
    .top37.tex39 insert end text
    vTcl:DefineAlias "$top.tex39" "txt_log" vTcl:WidgetProc "janela" 1
    button $top.but38 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Sair 
    vTcl:DefineAlias "$top.but38" "btn_sair" vTcl:WidgetProc "janela" 1
    bind $top.but38 <Button-1> {
        lambda e: btn_sair_clicked(e)
    }
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab39 \
        -in $top -x 10 -y 10 -width 330 -relwidth 0 -height 95 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab45 \
        -in $top -x 350 -y 10 -width 240 -relwidth 0 -height 95 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tex39 \
        -in $top -x 10 -y 120 -width 576 -relwidth 0 -height 292 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but38 \
        -in $top -x 540 -y 420 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top37 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

