# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'monitor.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setGeometry(200, 200, 640, 482)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.combo_box_portas = QtWidgets.QComboBox(self.groupBox)
        self.combo_box_portas.setObjectName("combo_box_portas")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.combo_box_portas)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.combo_box_bauds = QtWidgets.QComboBox(self.groupBox)
        self.combo_box_bauds.setObjectName("combo_box_bauds")
        self.combo_box_bauds.addItem("")
        self.combo_box_bauds.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.combo_box_bauds)
        self.horizontalLayout.addLayout(self.formLayout)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 620, 296))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.text_log = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.text_log.setFont(font)
        self.text_log.setObjectName("text_log")
        self.verticalLayout_2.addWidget(self.text_log)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMinimumSize(QtCore.QSize(0, 0))
        self.toolBar.setIconSize(QtCore.QSize(70, 32))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionConectar = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/connected.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionConectar.setIcon(icon)
        self.actionConectar.setObjectName("actionConectar")
        self.actionDesconectar = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../images/disconnected.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionDesconectar.setIcon(icon1)
        self.actionDesconectar.setObjectName("actionDesconectar")
        self.actionAtualizar = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../images/update.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionAtualizar.setIcon(icon2)
        self.actionAtualizar.setObjectName("actionAtualizar")
        self.actionSair = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../images/sair.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionSair.setIcon(icon3)
        self.actionSair.setObjectName("actionSair")
        self.actionLimpar = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../images/limpar.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionLimpar.setIcon(icon4)
        self.actionLimpar.setObjectName("actionLimpar")

        self.action_sobre = QtWidgets.QAction(QtGui.QIcon(
            "../images/sobre.png"), "Sobre", MainWindow)
        self.action_sobre.setShortcut("F12")

        self.combo_box_portas.setMinimumWidth(200)
        self.combo_box_bauds.setMinimumWidth(200)

        self.toolBar.addAction(self.actionConectar)
        self.toolBar.addAction(self.actionDesconectar)
        self.toolBar.addAction(self.actionAtualizar)
        self.toolBar.addAction(self.actionLimpar)
        self.toolBar.addAction(self.action_sobre)
        self.toolBar.addAction(self.actionSair)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Serial Monitor @dfso"))
        self.groupBox.setTitle(_translate("MainWindow", "Conexão"))
        self.label.setText(_translate("MainWindow", "Porta"))
        self.label_2.setText(_translate("MainWindow", "Baud Rate"))
        self.combo_box_bauds.setItemText(0, _translate("MainWindow", "9600"))
        self.combo_box_bauds.setItemText(1, _translate("MainWindow", "115200"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionConectar.setText(_translate("MainWindow", "Conectar"))
        self.actionConectar.setShortcut(_translate("MainWindow", "F3"))
        self.actionDesconectar.setText(_translate("MainWindow", "Desconectar"))
        self.actionDesconectar.setShortcut(_translate("MainWindow", "F7"))
        self.actionAtualizar.setText(_translate("MainWindow", "Atualizar"))
        self.actionAtualizar.setShortcut(_translate("MainWindow", "F5"))
        self.actionSair.setText(_translate("MainWindow", "Sair"))
        self.actionSair.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionLimpar.setText(_translate("MainWindow", "Limpar"))
        self.actionLimpar.setShortcut(_translate("MainWindow", "Ctrl+L"))

